version: '3.4'

services:
  nitro_vision:
    image: nitro_vision_ws
    network_mode: "host"
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./src:/ws/src
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev:/dev
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USERNAME: david
        USER_UID: 1000
    command: /bin/sh -c "while sleep 1000; do :; done"
